title: "Museum documentatie Naturalis"
baseURL: https://example.com/
footnoteReturnLinkContents: ↩
languageCode: "en-us"
params:
  AuthorName: Jon Doe
  GitHubUser: spf13
  SidebarRecentLimit: 5
  Subtitle: Documentatie t.b.v. ontwikkeling en beheer tentoonstellingen
  pluralizeListTitles: false
  disableInlineCopyToClipBoard: true
permalinks:
  post: /:year/:month/:title/
theme: "hugo-theme-learn"
outputs:
  home:
  - HTML
  - RSS
  - JSON
taxonomies:
  tentoonstelling: tentoonstellingen
  experience: experiences
  interactive: interactives
  component: componenten
